"""Add weather_locations table

Revision ID: 002
Revises: 001
Create Date: 2016-02-26 13:48:29.412293

"""

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_locations',
    sa.Column('nick', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('nick')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_locations')
    ### end Alembic commands ###
